#SPDX-License-Identifier: MIT-0
---
- name: Run setup tasks
  ansible.builtin.include_tasks: setup-{{ ansible_facts.os_family }}.yml

- name: Task is running from within the role
  ansible.builtin.debug:
    msg: "This is a task from my_role."
