#SPDX-License-Identifier: MIT-0
---
name: CI

on:
  push:
  pull_request:

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: make setup
      - name: Lint
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ !contains(github.event_name, 'pull_request') }}
      matrix:
        distro:
          - debian11
          - debian12
          - debian13
          - ubuntu2204
          - ubuntu2404
          - ubuntu2604
          - rockylinux9
          - rockylinux10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: make setup
      - name: Run tests
        run: make test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
